### ISSUE TITLE
The split filter should not crash the entire Logstash process when it receives un-splittable data

### ISSUE THREAD

**Issue by zackelan** [logstash-plugins/logstash-filter-split#17]
Repro:

Run Logstash 2.3 with the following config:

    input {
      http {
        port => 8888
      }
    }

    filter {
        json {
          source => "message"
          target => "data"
        }

        split {
          field => "data"
        }
    }

    output {
      stdout {
        codec => rubydebug
      }
    }

Send JSON data to Logstash that is valid JSON, but is a hash rather than an array:

    $ cat test.json 
    {
      "foo": 42,
      "bar": 9000
    }
    $ curl -XPOST --data @test.json  http://localhost:8888

Actual behavior:

Logstash writes a configuration error to stdout and the process exits.

    {:timestamp=>"2016-05-13T17:03:31.774000+0000", :message=>"Pipeline main started"}
    {:timestamp=>"2016-05-13T17:03:34.401000+0000", :message=>"Exception in pipelineworker, the pipeline stopped pr
    ocessing new events, please check your filter configuration and restart Logstash.", "exception"=>#<LogStash::Co
    nfigurationError: Only String and Array types are splittable. field:data is of type = Hash>, "backtrace"=>["/o$
    t/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-split-2.0.5/lib/logstash/filters/split.rb:49:in `filter
    '", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/filters/base.rb:151:in `m
    ulti_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-
    core-2.3.2-java/lib/logstash/filters/base.rb:148:in `multi_filter'", "(eval):67:in `filter_func'", "/opt/logsta
    sh/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:267:in `filter_batch'", "org/
    jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:852:in `inject'", "/opt/logstash/vendor/bu
    ndle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:265:in `filter_batch'", "/opt/logstash/ve
    ndor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:223:in `worker_loop'", "/opt/logst
    ash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:201:in `start_workers'"], :l
    evel=>:error}
    LogStash::ConfigurationError: Only String and Array types are splittable. field:data is of type = Hash
             filter at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-split-2.0.5/lib/logstash/filters/
    split.rb:49
       multi_filter at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/filters/bas
    e.rb:151
               each at org/jruby/RubyArray.java:1613
       multi_filter at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/filters/bas
    e.rb:148
        filter_func at (eval):67
       filter_batch at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb
    :267
               each at org/jruby/RubyArray.java:1613
             inject at org/jruby/RubyEnumerable.java:852
       filter_batch at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb
    :265
        worker_loop at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb
    :223
      start_workers at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb
    :201

Expected behavior:

Logstash should report an error and continue processing events.

Rationale:

If I send data through the JSON filter that isn't valid JSON, it does not bring down the entire Logstash pipeline, but instead tags the event as _jsonparsefailure and allows subsequent filters or outputs to process it. I think the split filter should behave similarly on invalid data.

**Comment by untergeek** [comment]
Thank you for reporting with a reproducible test.  This should be changed, I agree.

**Comment by andrewvc** [comment]
Thanks for the report! A new gem will be released shortly. This fix only went into the 5.x alpha series.

**Comment by pixelrebel** [comment]
This still occurs in 2.3.4:

```
{:timestamp=>"2016-08-03T09:21:45.620000-0700", :message=>"Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.", "exception"=>#<LogStash::ConfigurationError: Only String and Array types are splittable. field:[storage_groups] is of type = Hash>, "backtrace"=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-split-2.0.5/lib/logstash/filters/split.rb:49:in `filter'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/filters/base.rb:151:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/filters/base.rb:148:in `multi_filter'", "(eval):1971:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):1968:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):2027:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):2015:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):783:in `filter_func'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:267:in `filter_batch'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:852:in `inject'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:265:in `filter_batch'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:223:in `worker_loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:201:in `start_workers'"], :level=>:error}
```
