### ISSUE TITLE
Arrays with a null value cause Fatal error

### ISSUE THREAD

**Issue by jguay** [logstash-plugins/logstash-filter-split#33]
- Version: Logstash 6.0.1
- Config File (if you have sensitive info, please remove it):
```
input {
  stdin {
  codec => "json"
  }
}
filter {
split {
field => "field"
terminator => ","
}
}
output {
stdout {
codec => rubydebug
}
}
```
- Sample Data:
Non-working input : 
```
{"field":["value1", null, "value2"]} 
```
- Steps to Reproduce:
1) Run logstash with above config file
2) Copy/paste : {"field":["value1", null, "value2"]}[PRESS ENTER]
This result in fatal error
```
2017-12-11T13:50:12,879][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {:pipeline_id=>"main", "exception"=>"undefined method `empty?' for nil:NilClass", "backtrace"=>["/install_directory/logstash-6.0.1/vendor/bundle/jruby/2.3.0/gems/logstash-filter-split-3.1.5/lib/logstash/filters/split.rb:89:in `block in filter'", "org/jruby/RubyArray.java:1734:in `each'", "/install_directory/logstash-6.0.1/vendor/bundle/jruby/2.3.0/gems/logstash-filter-split-3.1.5/lib/logstash/filters/split.rb:88:in `filter'", "/install_directory/logstash-6.0.1/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", "/install_directory/logstash-6.0.1/logstash-core/lib/logstash/filters/base.rb:164:in `block in multi_filter'", "org/jruby/RubyArray.java:1734:in `each'", "/install_directory/logstash-6.0.1/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", "/install_directory/logstash-6.0.1/logstash-core/lib/logstash/filter_delegator.rb:48:in `multi_filter'", "(eval):42:in `block in filter_func'", "/install_directory/logstash-6.0.1/logstash-core/lib/logstash/pipeline.rb:501:in `filter_batch'", "/install_directory/logstash-6.0.1/logstash-core/lib/logstash/pipeline.rb:477:in `worker_loop'", "/install_directory/logstash-6.0.1/logstash-core/lib/logstash/pipeline.rb:439:in `block in start_workers'"], :thread=>"#<Thread:0x4d28331@/install_directory/logstash-6.0.1/logstash-core/lib/logstash/pipeline.rb:290 sleep>"}
[2017-12-11T13:50:12,908][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method `empty?' for nil:NilClass>, :backtrace=>["/install_directory/logstash-6.0.1/vendor/bundle/jruby/2.3.0/gems/logstash-filter-split-3.1.5/lib/logstash/filters/split.rb:89:in `block in filter'", "org/jruby/RubyArray.java:1734:in `each'", "/install_directory/logstash-6.0.1/vendor/bundle/jruby/2.3.0/gems/logstash-filter-split-3.1.5/lib/logstash/filters/split.rb:88:in `filter'", "/install_directory/logstash-6.0.1/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'", "/install_directory/logstash-6.0.1/logstash-core/lib/logstash/filters/base.rb:164:in `block in multi_filter'", "org/jruby/RubyArray.java:1734:in `each'", "/install_directory/logstash-6.0.1/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'", "/install_directory/logstash-6.0.1/logstash-core/lib/logstash/filter_delegator.rb:48:in `multi_filter'", "(eval):42:in `block in filter_func'", "/install_directory/logstash-6.0.1/logstash-core/lib/logstash/pipeline.rb:501:in `filter_batch'", "/install_directory/logstash-6.0.1/logstash-core/lib/logstash/pipeline.rb:477:in `worker_loop'", "/install_directory/logstash-6.0.1/logstash-core/lib/logstash/pipeline.rb:439:in `block in start_workers'"]}
```

**Comment by jakelandis** [comment]
Fixed with https://github.com/logstash-plugins/logstash-filter-split/pull/31 and released on `3.1.6`
